In [6]:
import os
import cv2
from deepface import DeepFace
import tensorflow as tf
import numpy

In [ ]:
model = 'liveness.model'
model = tf.keras.models.load_model(model)

In [4]:
dataset_path = 'D:\\SIC\\Project\\SIC_Project\\Face recognition data\\NewData'

Build model

In [5]:
DeepFace.build_model("Facenet")

In [8]:
cap = cv2.VideoCapture(0)
while True:
    
    state, frame = cap.read()
    
    if state!=True:
        break
        
    res  = DeepFace.find(frame, db_path= dataset_path, enforce_detection=False, model_name='VGG-Face')
    
    if len(res[0]['identity'])>0:
        
        name = res[0]['identity'][0].split('/')[1].split('\\')[1]
        xmin = int(res[0]['source_x'][0])
        ymin = int(res[0]['source_y'][0])
        
        w = res[0]['source_w'][0]
        h = res[0]['source_h'][0]
        
        xmax = int(xmin + w)
        ymax = int(ymin + h)
        
        #liveness
        
        img = frame[ymin:ymax, xmin:xmax]
        img = cv2.resize(img, (32,32))
        img = img.astype('float')/255.0
        img = tf.keras.preprocessing.image.img_to_array(img)
        img = numpy.expand_dims(img, axis=0)
        
        # liveness = model.predict(img)
        
        # liveness = liveness[0].argmax()
        
        
        
        cv2.rectangle(frame, (xmin,ymin),(xmax,ymax), (0,255,0),1)
        cv2.rectangle(frame, (xmin, ymin-25),(xmax, ymin),(255,255,255),-1)
        cv2.putText(frame, name, (xmin,ymin), cv2.FONT_HERSHEY_SIMPLEX, 1, (255,0,0),2,cv2.LINE_AA)
        
        # if liveness==1:
        #     cv2.putText(frame, "real", (xmin,ymax+25), cv2.FONT_HERSHEY_SIMPLEX, 1, (255,255,255),2, cv2.LINE_AA)
        # else:
        #     cv2.putText(frame, "fake", (xmin,ymax+25), cv2.FONT_HERSHEY_SIMPLEX, 1, (255,255,255),2, cv2.LINE_AA)
    
    cv2.imshow('attendance', frame)
    
    c = cv2.waitKey(1)
    
    if c == ord('q'):
        break
        
cap.release()
cv2.destroyAllWindows()

24-07-18 21:53:45 - Found 644 newly added image(s), 0 removed image(s), 0 replaced image(s).


Finding representations: 100%|██████████| 644/644 [09:04<00:00,  1.18it/s]


24-07-18 22:02:50 - There are now 644 representations in ds_model_vggface_detector_opencv_aligned_normalization_base_expand_0.pkl
24-07-18 22:02:50 - Searching [[[138 159 157]
  [144 157 147]
  [153 157 138]
  ...
  [ 55  53  60]
  [ 52  52  52]
  [ 56  56  55]]

 [[157 165 158]
  [159 162 156]
  [159 156 149]
  ...
  [ 50  54  53]
  [ 44  51  50]
  [ 48  55  55]]

 [[168 162 149]
  [165 162 149]
  [166 165 151]
  ...
  [ 49  56  58]
  [ 47  54  54]
  [ 53  60  59]]

 ...

 [[112 119 121]
  [112 119 121]
  [114 120 122]
  ...
  [ 89  96 108]
  [ 92 100 115]
  [ 92 100 115]]

 [[123 123 125]
  [125 124 126]
  [126 125 128]
  ...
  [ 95  97 111]
  [ 88  92 103]
  [ 88  92 103]]

 [[122 122 124]
  [125 124 125]
  [120 120 120]
  ...
  [ 97  98 114]
  [ 90  91 107]
  [ 90  91 107]]] in 644 length datastore
24-07-18 22:02:53 - find function duration 548.7480227947235 seconds


IndexError: list index out of range